# Dockerfile for python2 tests
# Installs dependencies and expects the `lib/` folder to be mapped to `/app`

FROM python:2.7

WORKDIR /app/lib

RUN sed -i 's|deb.debian.org|archive.debian.org|g' /etc/apt/sources.list && \
    sed -i '/security.debian.org/d' /etc/apt/sources.list && \
    apt update && \
    apt install -y protobuf-compiler

COPY tests/requirements-python2-dev.txt ./
RUN pip install -r requirements-python2-dev.txt
